# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hongdou' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 婚恋网
  pod 'SDWebImage', '~> 3.8.1'
  pod 'TZImagePreviewController', '~> 0.3.1'
  pod 'SCSiriWaveformView', '~> 1.1.1'
  pod 'ReactiveCocoa','~>2.1.8'
  
  pod 'SAMKeychain', '~> 1.5.0'
  pod 'AFDownloadRequestOperation', '~> 2.0.1'
  pod 'UIView+FDCollapsibleConstraints', '~> 1.1'
  
  pod 'AFNetworking', '~> 2.6.3'
  
  pod 'FMDB', '~> 2.6.2'
  
#  pod 'WebViewJavascriptBridge', '~> 5.1.2'
  pod 'hpple', '~> 0.2.0'
  
  pod 'Masonry', '1.1.0'
  
  pod 'MJRefresh'
  
  pod 'YYKit', '~> 1.0.9'
  
#  pod 'BRPickerView', '~> 2.7.0'
  pod 'JMessage', '~> 3.9.1'
  pod 'JPush', '3.7.4'
  pod 'BaiduMapKit', '~> 4.1.1'
  pod 'JXCategoryView', '~> 1.5.5'
  
  pod 'VODUpload', '~> 1.6.1'
  pod 'MBProgressHUD', '~> 1.0.0'

  pod 'JVerification'
  pod 'GDTMobSDK'
  pod 'SocketRocket'
  
end
